#!/usr/bin/env bash

##
## Description
##


# Check arguments
if [ $# -lt 3 ]; then
    echo "Usage: $(basename $0) <arg1> <arg2> <arg3>"
    exit 1
fi


# Access arguments
arg1="$1"
arg2="$2"
arg3="$3"


# Loop through all arguments using a for loop
for arg in "$@"; do
    echo "Argument: $arg"
done

